# Configuración de despliegue para Dokploy
# =================================================

version: '1'
name: core-directus-nextjs

services:
  # Base de datos PostgreSQL
  database:
    image: postgres:17.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Directus CMS
  directus:
    build: ./directus
    depends_on:
      database:
        condition: service_healthy
    environment:
      - KEY=${DIRECTUS_KEY}
      - SECRET=${DIRECTUS_SECRET}
      - ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}
      - DB_CLIENT=pg
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
      - directus_data:/directus/data

  # Aplicación Next.js
  app:
    build: ./app
    depends_on:
      - directus
    environment:
      - NEXT_PUBLIC_DIRECTUS_URL=${DIRECTUS_PUBLIC_URL}

volumes:
  postgres_data:
  directus_uploads:
  directus_extensions:
  directus_data:

# Configuración específica de Dokploy
dokploy:
  # Configuración de recursos
  resources:
    database:
      cpu: 1
      memory: 2G
    directus:
      cpu: 1
      memory: 1.5G
    app:
      cpu: 1
      memory: 1G

  # Rutas de acceso público
  routes:
    app:
      - domain: ${APP_DOMAIN}
        path: /
    directus:
      - domain: ${DIRECTUS_DOMAIN}
        path: /

  # Hooks para ejecutar antes/después del despliegue
  hooks:
    predeploy:
      - echo "Iniciando despliegue..."
    postdeploy:
      - echo "Aplicando snapshot del esquema de base de datos..."
      - /scripts/apply-snapshot.sh

  # Variables de entorno para Dokploy
  env_groups:
    - name: database
      description: "Variables para PostgreSQL"
      vars:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
    - name: directus
      description: "Variables para Directus"
      vars:
        - DIRECTUS_KEY
        - DIRECTUS_SECRET
        - DIRECTUS_ADMIN_EMAIL
        - DIRECTUS_ADMIN_PASSWORD
        - DIRECTUS_PUBLIC_URL
    - name: app
      description: "Variables para Next.js"
      vars:
        - APP_DOMAIN
        - DIRECTUS_DOMAIN
